apiVersion: crd.flyinpancake.com/v1
kind: ClusterClassroom
metadata:
  labels:
    app.kubernetes.io/name: clusterclassroom
    app.kubernetes.io/managed-by: kustomize
  name: clusterclassroom-sample
spec:
  # TODO(user): Add fields here
  namespacePrefix: "student"
  constructor:
    image: "localhost/ctor"
    command:
      - /create-nginx.sh
    args: []
    backoffLimit: 3
    imagePullPolicy: "Never"
  evaluator:
    image: "localhost/eval"
    command: ["/evaluate-cluster.sh"]
    backoffLimit: 3
    imagePullPolicy: "Never"
  studentId: "ABC123"
