# permissions for end users to view clusterclassrooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterclassroom
    app.kubernetes.io/managed-by: kustomize
  name: clusterclassroom-viewer-role
rules:
- apiGroups:
  - crd.flyinpancake.com
  resources:
  - clusterclassrooms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.flyinpancake.com
  resources:
  - clusterclassrooms/status
  verbs:
  - get
