---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.flyinpancake.com
  resources:
  - clusterclassrooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.flyinpancake.com
  resources:
  - clusterclassrooms/finalizers
  verbs:
  - update
- apiGroups:
  - crd.flyinpancake.com
  resources:
  - clusterclassrooms/status
  verbs:
  - get
  - patch
  - update
