FROM alpine:3.20

# Install kubectl

RUN apk add --no-cache curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

COPY evaluate-cluster.sh /

RUN chmod +x /evaluate-cluster.sh

CMD ["/evaluate-cluster.sh"]