# run on pushing a tag
on:
  push:
    tags:
      - 'v*'
permissions: 
  contents: write
  packages: write
  deployments: write
  pages: write

    
    
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
jobs:
    build_cli:
        name: Build CLI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Build CLI
              run: cargo build --release
              working-directory: ./cli
            - name: Rename binary
              run: mv ./cli/target/release/cccli ./cli/target/release/cccli-unknown-linux-gnu-${{ github.ref_name }}
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./cli/target/release/cccli-unknown-linux-gnu-${{ github.ref_name }}
    
    build_controller:
        name: Build Controller
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Change String Case
              uses: ASzc/change-string-case-action@v6
              with:
                string: ${{ env.IMAGE_NAME }}
              id: image-name
            - name: Build Docker image
              run: make docker-build IMG=${{ env.REGISTRY }}/${{ steps.image-name.outputs.lowercase }}:${{ env.IMAGE_TAG }}
              working-directory: controller

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Docker image
              run: make docker-push IMG=${{ env.REGISTRY }}/${{ steps.image-name.outputs.lowercase }}:${{ env.IMAGE_TAG }}
              working-directory: controller
    
            